CoffeTownNET8/Areas/Admin/Controllers/CategoriasController.cs
using CoffeTownNET8.AccesoDatos.Data.Repository.IRepository;
using CoffeTownNET8.Modelos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoffeTownNET8.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrador")]
    [Area("Admin")]
    public class CategoriasController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public CategoriasController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        //[AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Categoria.Add(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Categoria categoria = new Categoria();
            categoria = _contenedorTrabajo.Categoria.Get(id);

            if(categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Categoria.Update(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        #region LLAMADAS A LA API

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new {data = _contenedorTrabajo.Categoria.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _contenedorTrabajo.Categoria.Get(id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Error al borrar la tipo de café" });
            }
            _contenedorTrabajo.Categoria.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Tipo de café borrado correctamente" });
        }

        #endregion
    }
}

CoffeTownNET8/Areas/Admin/Controllers/PedidosController.cs
using CoffeTownNET8.AccesoDatos.Data.Repository.IRepository;
using CoffeTownNET8.Modelos;
using CoffeTownNET8.Modelos.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoffeTownNET8.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrador")]
    [Area("Admin")]
    public class PedidosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public PedidosController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            PedidoVM pedidoVM = new PedidoVM()
            {
                Pedido = new CoffeTownNET8.Modelos.Pedido(),
                ListaProductos = _contenedorTrabajo.Producto.GetListaProductos()
            };

            return View(pedidoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PedidoVM pedidoVM)
        {
            var productoFromDb = _contenedorTrabajo.Producto.Get(pedidoVM.Pedido.ProductoId);
            if (ModelState.IsValid)
            {
                pedidoVM.Pedido.MontoTotal = (float)(pedidoVM.Pedido.Cantidad * productoFromDb.Precio);

                pedidoVM.Pedido.FechaVenta = DateTime.Now.ToString();
                _contenedorTrabajo.Pedido.Add(pedidoVM.Pedido);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            pedidoVM.ListaProductos = _contenedorTrabajo.Producto.GetListaProductos();
            return View(pedidoVM);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            PedidoVM pedidoVM = new PedidoVM()
            {
                Pedido = new Modelos.Pedido(),
                ListaProductos = _contenedorTrabajo.Producto.GetListaProductos(),

            };

            if (id != null)
            {
                pedidoVM.Pedido = _contenedorTrabajo.Pedido.Get(id.GetValueOrDefault());
            }

            return View(pedidoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PedidoVM pedidoVM)
        {
            if (ModelState.IsValid)
            {
                var productoFromDb = _contenedorTrabajo.Producto.Get(pedidoVM.Pedido.ProductoId);
                if (ModelState.IsValid)
                {
                    pedidoVM.Pedido.MontoTotal = (float)(pedidoVM.Pedido.Cantidad * productoFromDb.Precio);

                    _contenedorTrabajo.Pedido.Update(pedidoVM.Pedido);
                    _contenedorTrabajo.Save();
                    return RedirectToAction(nameof(Index));
                }
                pedidoVM.ListaProductos = _contenedorTrabajo.Producto.GetListaProductos();
                return View(pedidoVM);
            }
            pedidoVM.ListaProductos = _contenedorTrabajo.Producto.GetListaProductos();
            return View(pedidoVM);
        }


        #region LLAMADAS A LA API
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Pedido.GetAll(includeProperties: "Producto") });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _contenedorTrabajo.Pedido.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error al borrar el pedido" });
            }
            _contenedorTrabajo.Pedido.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Pedido borrado con éxito" });
        }

        #endregion
    }
}

CoffeTownNET8/Areas/Admin/Controllers/SlidersController.cs
using CoffeTownNET8.AccesoDatos.Data.Repository.IRepository;
using CoffeTownNET8.Modelos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoffeTownNET8.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrador")]

    [Area("Admin")]
    public class SlidersController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public SlidersController(IContenedorTrabajo contenedorTrabajo,
            IWebHostEnvironment hostingEnvironment)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Slider slider)
        {
            if (ModelState.IsValid)
            {
                string rutaPrincipal = _hostingEnvironment.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;

                if (archivos.Count() > 0)
                {
                    //Nuevo slider
                    string nombreArchivo = Guid.NewGuid().ToString();
                    var subidas = Path.Combine(rutaPrincipal, @"img\sliders");
                    var extension = Path.GetExtension(archivos[0].FileName);

                    using (var fileStreams = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                    {
                        archivos[0].CopyTo(fileStreams);
                    }

                    slider.UrlImagen = @"\img\sliders\" + nombreArchivo + extension;

                    _contenedorTrabajo.Slider.Add(slider);
                    _contenedorTrabajo.Save();

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Imagen", "Debes seleccionar una imagen");
                }

            }

            return View(slider);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {

            if (id != null)
            {
                var slider = _contenedorTrabajo.Slider.Get(id.GetValueOrDefault());
                return View(slider);
            }

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Slider slider)
        {
            if (ModelState.IsValid)
            {
                string rutaPrincipal = _hostingEnvironment.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;

                var sliderDdesdeBd = _contenedorTrabajo.Slider.Get(slider.Id);

                if (archivos.Count() > 0)
                {
                    //Nuevo imagen slider
                    string nombreArchivo = Guid.NewGuid().ToString();
                    var subidas = Path.Combine(rutaPrincipal, @"img\sliders");
                    var extension = Path.GetExtension(archivos[0].FileName);

                    //var nuevaExtension = Path.GetExtension(archivos[0].FileName);

                    var rutaImagen = Path.Combine(rutaPrincipal, sliderDdesdeBd.UrlImagen.TrimStart('\\'));

                    if (System.IO.File.Exists(rutaImagen))
                    {
                        System.IO.File.Delete(rutaImagen);
                    }

                    //Nuevamente subimos el archivo
                    using (var fileStreams = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                    {
                        archivos[0].CopyTo(fileStreams);
                    }


                    slider.UrlImagen = @"\img\sliders\" + nombreArchivo + extension;

                    _contenedorTrabajo.Slider.Update(slider);
                    _contenedorTrabajo.Save();

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    //Aquí sería cuando la imagen ya existe y se conserva
                    slider.UrlImagen = sliderDdesdeBd.UrlImagen;
                }

                _contenedorTrabajo.Slider.Update(slider);
                _contenedorTrabajo.Save();

                return RedirectToAction(nameof(Index));

            }

            return View(slider);
        }




        #region Llamadas a la API
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Slider.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var sliderDesdeBd = _contenedorTrabajo.Slider.Get(id);
            string rutaDirectorioPrincipal = _hostingEnvironment.WebRootPath;
            var rutaImagen = Path.Combine(rutaDirectorioPrincipal, sliderDesdeBd.UrlImagen.TrimStart('\\'));
            if (System.IO.File.Exists(rutaImagen))
            {
                System.IO.File.Delete(rutaImagen);
            }


            if (sliderDesdeBd == null)
            {
                return Json(new { success = false, message = "Error borrando slider" });
            }

            _contenedorTrabajo.Slider.Remove(sliderDesdeBd);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Slider Borrado Correctamente" });
        }
        #endregion
    }
}

CoffeTownNET8/Areas/Admin/Controllers/UsuariosController.cs
using CoffeTownNET8.AccesoDatos.Data.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CoffeTownNET8.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrador")]
    [Area("Admin")]

    public class UsuariosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public UsuariosController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //Opcion 1: Obtener todos los usuarios
            //return View(_contenedorTrabajo.Usuario.GetAll());

            //opcion2
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var usuarioActual = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(_contenedorTrabajo.Usuario.GetAll(u => u.Id != usuarioActual.Value));
        }

        [HttpGet]
        public IActionResult Bloquear(string id)
        {
            if(id == null)
            {
                return NotFound();
            }
            _contenedorTrabajo.Usuario.BloquearUsuario(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Desbloquear(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _contenedorTrabajo.Usuario.DesbloquearUsuario(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

CoffeTownNET8/Areas/Admin/Controllers/VentasController.cs
using CoffeTownNET8.AccesoDatos.Data.Repository.IRepository;
using CoffeTownNET8.Modelos;
using CoffeTownNET8.Modelos.ViewModels;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace CoffeTownNET8.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrador")]
    [Area("Admin")]
    public class VentasController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly UserManager<AplicationUser> _userManager;

        public VentasController(IContenedorTrabajo contenedorTrabajo, UserManager<AplicationUser> userManager)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create(int? id)
        {
            PedidoVM pedidoVM = new PedidoVM()
            {
                Pedido = new CoffeTownNET8.Modelos.Pedido(),
                ListaProductos = _contenedorTrabajo.Producto.GetListaProductos()
            };

            if (id != null)
            {
                pedidoVM.Pedido = _contenedorTrabajo.Pedido.Get(id.GetValueOrDefault());
            }

            return View(pedidoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PedidoVM pedidoVM)
        {
            if (ModelState.IsValid)
            {

                // Mapear los datos de PedidoVM a Venta
                Venta venta = new Venta
                {
                    FechaVenta = pedidoVM.Pedido.FechaVenta,
                    Nombre = pedidoVM.Pedido.Nombre,
                    ProductoId = pedidoVM.Pedido.ProductoId,
                    Cantidad = pedidoVM.Pedido.Cantidad,
                    MontoTotal = pedidoVM.Pedido.MontoTotal
                };

                _contenedorTrabajo.Venta.Add(venta);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }

            pedidoVM.ListaProductos = _contenedorTrabajo.Producto.GetListaProductos();
            return View(pedidoVM);
        }

        #region LLAMADAS A LA API

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Venta.GetAll(includeProperties: "Producto") });
        }

        #endregion
    }
}

CoffeTownNET8/Views/Shared/_Layout.cshtml
@using CoffeTownNET8.Utilidades
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoffeTown</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap5.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/CoffeTownNET8.styles.css" asp-append-version="true" /> *@

    <!--Css todos-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.7/sweetalert2.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

</head>
<body class="hold-transition layout-top-nav layout-navbar-fixed layout-footer-fixed" style="background-color: white">
    <div class="wrapper">
        <div class="preloader flex-column justify-content-center align-items-center" style="background-color: #2b2b2b">
            <img class="animation__wobble img-circle" src="~/img/Logo_CoffeeTown.png" alt="LogoCoffeTown" height="250" width="250">
        </div>
        <header class="main-header pt-2 px-2" style="background-color: transparent; border: none !important;">
            <nav class="layout-navbar-fixed navbar navbar-expand-lg p-3" style="background-color: #895D58" data-bs-theme="dark">
                <div class="container-fluid">
                    <a class="mx-3" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/img/Logo_CoffeeTown.png" alt="CoffeTown" height="50" width="50" />
                    </a>
                    <a class="navbar-brand" style="font-size: 30px" asp-area="" asp-controller="Home" asp-action="Index">CoffeTown</a>
                    @if (User.IsInRole(CNT.Administrador))
                    {
                        <div class="separator-vertical mx-3" style="background-color: #fff; width: 2px; height: 25px;"></div>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    }
                    <div class="collapse navbar-collapse" id="navbarColor01">
                        <ul class="navbar-nav me-auto">
                            <!--Autorizacion-->
                            @if(User.IsInRole(CNT.Administrador)){
                                <li class="nav-item dropdown">
                                    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                                        <button type="button" class="btn btn-secondary" style="outline: none; box-shadow: 0 0 0 0.1rem black;" onFocus="this.style.boxShadow = '0 0 0 0.2rem black)'">Menú</button>
                                        <div class="btn-group" role="group">
                                            <button id="btnGroupDrop1" type="button" style="outline: none; box-shadow: 0 0 0 0.1rem black;" onFocus="this.style.boxShadow = '0 0 0 0.2rem black)'" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                                            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1" style="">
                                                <a class="text-white dropdown-item" asp-area="Admin" asp-controller="Categorias" asp-action="Index"><i class="mr-4 fas fa-th-large"></i>Categorías</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="text-white dropdown-item" asp-area="Admin" asp-controller="Productos" asp-action="Index"><i class="mr-4 nav-icon fas fa-box-open"></i>Productos</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="text-white dropdown-item" asp-area="Admin" asp-controller="Sliders" asp-action="Index"><i class="mr-4 fa-solid fa-dollar-sign"></i>Promociones</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="text-white dropdown-item" asp-area="Admin" asp-controller="Pedidos" asp-action="Index"><i class="mr-4 fa-solid fa-mug-hot"></i>Pedidos</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="text-white dropdown-item" asp-area="Admin" asp-controller="Ventas" asp-action="Index"><i class="mr-4 fas fa-cash-register"></i>Ventas</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="text-white dropdown-item" asp-area="Admin" asp-controller="Usuarios" asp-action="Index"><i class="mr-4 fa-solid fa-user"></i>Usuarios</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            }
                            
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>

            <!--Aquí vista parcial slider-->
            @if (ViewBag.IsHome == true)
            {
               // <partial name="_Slider" />
            }

        </header>
        <div>
            <main role="main">
                @RenderBody()
            </main>
        </div>

        <footer class="main-footer" style="background-color: #895D58">
            <div class="container" style="color: white">
                &copy; 2024 - CoffeTownNET8 - @ViewData["Title"]
            </div>
        </footer>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!--Js plugins-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.7/sweetalert2.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CoffeTownNET8/Views/Shared/_Slider.cshtml
 @model CoffeTownNET8.Modelos.ViewModels.HomeVM
<!--Slider-->
<div id="sliderImagenes" class="carousel slide">   
    <div class="carousel-inner">
        @{
            int cont = 0;
        }

        @foreach (var slider in Model.Sliders)
        {
            var itemDinamico = cont++ == 0 ? "active" : "";

            @if (slider.Estado == true)
            {
                <div class="carousel-item @itemDinamico">
                    <img src="@Url.Content(slider.UrlImagen)" class="d-block w-100">
                    <h1 class="text-white text-center bg-dark py-1">@Html.Raw(slider.Nombre)</h1>
                </div>
            }
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#sliderImagenes" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#sliderImagenes" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<!--Cierra Slider-->

CoffeTownNET8/Views/Shared/_VistaCrearVolver.cshtml
<div class="row mt-2">
    <div class="col">
        <button type="submit" class="btn form-control" style="background-color: #c96442; color: white; font-size: 16px; outline: none; box-shadow: 0 0 0 0.1rem black;" onFocus="this.style.boxShadow = '0 0 0 0.2rem black)'">Guardar &nbsp<i class="fas fa-save"></i></button>
    </div>
    &nbsp;
    <div class="col">
        <a asp-action="Index" class="btn btn-secondary form-control" style="outline: none; box-shadow: 0 0 0 0.1rem black;" onFocus="this.style.boxShadow = '0 0 0 0.2rem black)'">Volver a la lista &nbsp; <i class="fas fa-reply"></i></a>
    </div>
</div>

CoffeTownNET8/Views/Shared/_VistaEditarVolver.cshtml
<div class="row mt-2">
    <div class="col">
        <button type="submit" class="btn form-control" style="background-color: #c96442; color: white; font-size: 16px; outline: none; box-shadow: 0 0 0 0.1rem black;" onFocus="this.style.boxShadow = '0 0 0 0.2rem black)'">Editar &nbsp; <i class="fas fa-pen-alt"></i></i></button>
    </div>
    &nbsp;
    <div class="col">
        <a asp-action="Index" class="btn btn-secondary form-control" style="outline: none; box-shadow: 0 0 0 0.1rem black;" onFocus="this.style.boxShadow = '0 0 0 0.2rem black)'">Volver a la lista &nbsp; <i class="fas fa-reply"></i></a>
    </div>
</div>