CoffeTownNET8/Areas/Admin/Controllers/PDFController.cs
using CoffeTownNET8.AccesoDatos.Data.Repository.IRepository;
using CoffeTownNET8.Modelos.ViewModels;
using CoffeTownNET8.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using CoffeTownNET8.Areas.Admin.Controllers;
using Microsoft.EntityFrameworkCore.Metadata;
using CoffeTownNET8.Modelos;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace CoffeTownNET8.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PDFController : Controller
    {
        private readonly IWebHostEnvironment _host;
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public PDFController(IWebHostEnvironment host, IContenedorTrabajo contenedorTrabajo)
        {
            _host = host;
            _contenedorTrabajo = contenedorTrabajo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ventaPDF()
        {
            var venta = _contenedorTrabajo.Venta.GetAll(includeProperties: "Producto"); // Obtener la lista de empleados desde el repositorio

            
            var PDF = Document.Create(document =>
            {
                document.Page(page =>
                {
                    page.Margin(30);

                    page.Header().ShowOnce().Row(row =>
                    {
                        var rutaImagen = Path.Combine(_host.WebRootPath, "img/Logo_CoffeeTown.png");
                        byte[] imageData = System.IO.File.ReadAllBytes(rutaImagen);

                        row.ConstantItem(80).Image(imageData);

                        row.RelativeItem().Column(col =>
                        {
                            col.Item().AlignCenter().Text("Coffe Town").Bold().FontSize(14);
                            col.Item().AlignCenter().Text("col. Las Mercedes").FontSize(9);
                            col.Item().AlignCenter().Text("79245635").FontSize(9);
                            col.Item().AlignCenter().Text("coffetown@gmail.com").FontSize(9);
                        });

                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Border(1).BorderColor("#895d58")
                            .AlignCenter().Text("RUC 21312312312");

                            col.Item().Border(1).Background("#895d58").BorderColor("#895d58")
                            .AlignCenter().Text("Boleta de Ventas").FontColor("#ffff");

                            col.Item().Border(1).BorderColor("#895d58")
                            .AlignCenter().Text("B001-234");
                        });
                    });

                    page.Content().PaddingVertical(10).Column(col1 =>
                    {
                        col1.Item().Column(col2 =>
                        {
                            col2.Item().Text("Datos Sucursal").Underline().Bold();

                            col2.Item().Text(txt =>
                            {
                                txt.Span("Sucursal: ").SemiBold().FontSize(10);
                                txt.Span("Ilobasco").FontSize(10);

                            });

                            col2.Item().Text(txt =>
                            {
                                txt.Span("Direccion: ").SemiBold().FontSize(10);
                                txt.Span("col. Las Mercedes").FontSize(10);
                            });
                        });

                        col1.Item().LineHorizontal(0.5f);

                        col1.Item().Table(tabla =>
                        {
                            tabla.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(2);
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                            });

                            tabla.Header(header =>
                            {
                                header.Cell().Background("#895d58")
                                .Padding(2).Text("Producto").FontColor("#fff");

                                header.Cell().Background("#895d58")
                                .Padding(2).Text("Cantidad").FontColor("#fff");

                                header.Cell().Background("#895d58")
                                .Padding(2).Text("Cliente").FontColor("#fff");

                                header.Cell().Background("#895d58")
                                .Padding(2).Text("Fecha").FontColor("#fff");

                                header.Cell().Background("#895d58")
                                .Padding(2).Text("Total").FontColor("#fff");

                            });

                            foreach (var item in venta)
                            {

                                tabla.Cell().BorderBottom(0.5f).BorderColor("#D9D9D9")
                                .Padding(2).Text(item.Producto.Nombre).FontSize(10);

                                tabla.Cell().BorderBottom(0.5f).BorderColor("#D9D9D9")
                                .Padding(2).Text(item.Cantidad).FontSize(10);

                                tabla.Cell().BorderBottom(0.5f).BorderColor("#D9D9D9")
                                .Padding(2).Text(item.Nombre).FontSize(10);

                                tabla.Cell().BorderBottom(0.5f).BorderColor("#D9D9D9")
                                .Padding(2).Text(item.FechaVenta).FontSize(10);

                                tabla.Cell().BorderBottom(0.5f).BorderColor("#D9D9D9")
                                .Padding(2).Text($"${item.MontoTotal}").FontSize(10);

                            };
                        });
                        //var totalPrice = Model.Items.Sum(x => x.Price * x.Quantity);
                        //col1.Item().AlignRight().Text($"total: {totalPrice}").FontSize(12);

                        col1.Spacing(10);
                    });

                    page.Footer().AlignRight().Text(txt =>
                    {
                        txt.Span("Pagina ").FontSize(10);
                        txt.CurrentPageNumber().FontSize(10);
                        txt.Span(" de ").FontSize(10);
                        txt.TotalPages().FontSize(10);


                    });
                });
            }).GeneratePdf();
            
            Stream stream = new MemoryStream(PDF);
            return File(stream, "application/pdf", "reporteVenta.pdf");

            return View();
        }
    }
}

CoffeTownNET8/Areas/Admin/Controllers/VentasController.cs
using CoffeTownNET8.AccesoDatos.Data.Repository.IRepository;
using CoffeTownNET8.Modelos;
using CoffeTownNET8.Modelos.ViewModels;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace CoffeTownNET8.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrador")]
    [Area("Admin")]
    public class VentasController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly UserManager<AplicationUser> _userManager;

        public VentasController(IContenedorTrabajo contenedorTrabajo, UserManager<AplicationUser> userManager)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create(int? id)
        {
            PedidoVM pedidoVM = new PedidoVM()
            {
                Pedido = new CoffeTownNET8.Modelos.Pedido(),
                ListaProductos = _contenedorTrabajo.Producto.GetListaProductos()
            };

            if (id != null)
            {
                pedidoVM.Pedido = _contenedorTrabajo.Pedido.Get(id.GetValueOrDefault());
            }

            return View(pedidoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PedidoVM pedidoVM)
        {
            if (ModelState.IsValid)
            {

                // Mapear los datos de PedidoVM a Venta
                Venta venta = new Venta
                {
                    FechaVenta = pedidoVM.Pedido.FechaVenta,
                    Nombre = pedidoVM.Pedido.Nombre,
                    ProductoId = pedidoVM.Pedido.ProductoId,
                    Cantidad = pedidoVM.Pedido.Cantidad,
                    MontoTotal = pedidoVM.Pedido.MontoTotal
                };

                _contenedorTrabajo.Venta.Add(venta);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }

            pedidoVM.ListaProductos = _contenedorTrabajo.Producto.GetListaProductos();
            return View(pedidoVM);
        }

        #region LLAMADAS A LA API

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Venta.GetAll(includeProperties: "Producto") });
        }

        #endregion
    }
}

CoffeTownNET8/Areas/Admin/Views/Ventas/Create.cshtml
@model CoffeTownNET8.Modelos.ViewModels.PedidoVM

@{
    ViewData["Title"] = "Crear pedido";
}

<div style="padding-top: 130px;">
    <div class="container">
        <form method="post" asp-action="Create">
            <input type="hidden" asp-for="Pedido.Id" />
            <div class="card">
                <div class="card-body">
                    <h2 class=" card-header text-center" style="background-color: transparent">Crear un nuevo pedido</h2>
                    <div class="row  px-2 mt-2">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <!-- Columna para la imagen -->
                        <div class="col-md-4">
                            <img src="~/img/tazacafe-crear.png" alt="TazaCafe" class="img-fluid" />
                        </div>

                        <!-- Columna para el formulario -->
                        <div class="col-md-8 mt-4 d-flex flex-column justify-content-between">
                            <div class="form-group row">
                                <div class="col-4">
                                    <label asp-for="Pedido.FechaVenta" class="control-label"></label>
                                </div>
                                <div class="col-8">
                                    <input asp-for="Pedido.FechaVenta" class="form-control" placeholder="Ingrese un nombre para identificar el pedido" />
                                    <span asp-validation-for="Pedido.FechaVenta" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-4">
                                    <label asp-for="Pedido.Nombre" class="control-label"></label>
                                </div>
                                <div class="col-8">
                                    <input asp-for="Pedido.Nombre" class="form-control" placeholder="Ingrese un nombre para identificar el pedido" />
                                    <span asp-validation-for="Pedido.Nombre" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-4">
                                    <label asp-for="Pedido.ProductoId"></label>
                                </div>
                                <div class="col-8 ">
                                    @Html.DropDownListFor(m => m.Pedido.ProductoId, Model.ListaProductos,
                                             "Seleccione un producto", new { @class = "form-control" })
                                    <span asp-validation-for="Pedido.ProductoId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-4">
                                    <label asp-for="Pedido.Cantidad" class="control-label"></label>
                                </div>
                                <div class="col-8 ">
                                    <input asp-for="Pedido.Cantidad" class="form-control " placeholder="Ingrese la cantidad" />
                                    <span asp-validation-for="Pedido.Cantidad" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-4">
                                    <label asp-for="Pedido.MontoTotal" class="control-label"></label>
                                </div>
                                <div class="col-8">
                                    <input asp-for="Pedido.MontoTotal" class="form-control" placeholder="Ingrese un nombre para identificar el pedido" />
                                    <span asp-validation-for="Pedido.MontoTotal" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row mt-auto">
                                <div class="col">
                                    <partial name="_VistaCrearVolver" />
                                    <br />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

CoffeTownNET8/Areas/Admin/Views/Ventas/Index.cshtml
@{
    ViewData["Title"] = "Lista de ventas";
}


<div style="padding-top: 130px">
    <div class="container">
        <div class="row">
            <div class="col-8">
                <h1 class="text-primary">Lista de Ventas</h1>
            </div>
            <div class="col-4 text-right">
                <a href="/Admin/Pedidos/Index" class="btn btn-secondary" style="outline: none; box-shadow: 0 0 0 0.1rem black;" onFocus="this.style.boxShadow = '0 0 0 0.2rem black)'">Ver mas pedidos<i class="fa fa-eye mx-2" aria-hidden="true"></i></a>
            </div>
        </div>
        <br />
        <table id="tblVentas" class="table table-secondary table-hover table-striped table-bordered" style="width: 100%; ">
            <thead>
                <tr>
                    <th class="text-center">Fecha</th>
                    <th class="text-center">Nombre</th>
                    <th class="text-center">Producto</th>
                    <th class="text-center">Cantidad</th>
                    <th class="text-center">Monto total</th>
                </tr>
            </thead>
        </table>
        <form asp-action="ventaPDF" asp-controller="PDF">
            <button style="background-color: #895d58" class="btn text-white" type="submit"><i class="fa-solid fa-file-pdf"></i>&nbspDescargar PDF</button>
        </form>
    </div>
</div>

@section Scripts {
    <script src="~/js/ventas.js"></script>
}